<?php

namespace AppBundle\Repository;

/**
 * AvantageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvantageRepository extends \Doctrine\ORM\EntityRepository
{
  /**
    * Recherche de l'article de la rubrique avantage
    *
    * Author: Delrodie AMOIKON
    * Date: 14/02/2017
    * Since: v1.0
    */
    public function getAvantage()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
            SELECT a
            FROM AppBundle:Avantage a
            WHERE a.statut = :stat
        ')
          ->setParameter('stat', 1)
        ;
        try {
            $result = $qb->getResult();

            return $result;

        } catch (NoResultException $e) {
            return $e;
        }
    }
}
